# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d19de688215ae19fd06bc559b665f0cd1e057c19291a62fb1e90d40c45ae4cc68ce8cdf4e7318726090e51a7ffd4902f42a40e3e3b4b01cb6d4f0d85fa597208

test:
  secret_key_base: 1473b1a1415cf3a3c48ed9fced3e4d8912732c040d1c79aea4d8aeca635e3bc39043fdb62d1cd9fc0b53c7d27a2c9e5d51a5e943a465fea98ad98773e3d6f66e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
